Workspace management
========================================================

Installing a package
--------------------------------------------------------------------------------

From inside the workspace.
```{r, eval=FALSE}
install.packages('knitr')
```

From outside any R session
Download from CRAN, by ex. http://cran.r-project.org/web/packages/knitr/index.html
```{r, eval=FALSE}
R CMD INSTALL knitr
```

List loaded packages
--------------------------------------------------------------------------------

Get a global view of the current session. In reproducible research, this information is important to keep after a data analysis, in order to be able to re-set the same environment.

```{r}
sessionInfo()
```

Get the list of all currently loaded packages, and a few information on them.

```{r}
installed.packages()[.packages(),]
```

Load/detach a package
--------------------------------------------------------------------------------

```{r, eval=FALSE}
## Detach a package
detach("package:affy", unload=TRUE)

## Load a package
library("Biobase", lib.loc="/home/chernan/R/i686-pc-linux-gnu-library/2.15")

## Write the list in a file
instPackages <- installed.packages()[.packages(),]
write.table(instPackages, "loadedPackages.txt", quote=TRUE)

## Load packages from a file
packagesToLoad <- read.table("loadedPackages.txt", header=TRUE, stringsAsFactors=FALSE)
apply(packagesToLoad, 1, FUN=function(aLib){ 
    library(package=aLib["Package"], lib.loc=aLib["LibPath"], character.only=TRUE)
})
```
